package org.dosfer.receiver;

import org.junit.Test;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import static org.junit.Assert.*;

public class ProtocolTest {
    @Test public void firstPlaneGroupUsesZeroGroupIdAndExplicitWidth(){
        byte[] payload=record(1,12);
        Protocol.Frame plane3=Protocol.parseFrame(Protocol.encodeFrame(Protocol.PLANE_CODED,0,0x12345678L,0,1,0,3,0,3,payload));
        Protocol.Frame plane4=Protocol.parseFrame(Protocol.encodeFrame(Protocol.PLANE_CODED,0,0x12345678L,0,1,0,4,0,4,payload));
        assertEquals(0,plane3.streamId);assertEquals(3,plane3.streamOffset);assertTrue(SessionStore.isPlaneStart(plane3));
        assertEquals(0,plane4.streamId);assertEquals(4,plane4.streamOffset);assertTrue(SessionStore.isPlaneStart(plane4));
    }
    @Test public void planeWindow128KeepsZeroFirstGroupAndExplicitWidth(){
        byte[] payload=record(1,12);
        Protocol.Frame first=Protocol.parseFrame(Protocol.encodeFrame(Protocol.PLANE_CODED,0,0x12345678L,9,1,0,128,0,4,payload));
        Protocol.Frame finalBasis=Protocol.parseFrame(Protocol.encodeFrame(Protocol.PLANE_CODED,0,0x12345678L,9,4,124,128,124,4,payload));
        assertEquals(128,first.windowCount);assertEquals(0,first.streamId);assertTrue(SessionStore.isPlaneStart(first));
        assertEquals(128,finalBasis.windowCount);assertEquals(4,finalBasis.streamOffset);assertEquals(124,finalBasis.streamId);
    }
    @Test public void planeCodedOddEquationsRoundTripAndSolve(){
        byte[][] basis={record(100,32),record(101,32),record(102,32),record(103,32)};int[] c={1,2,4,8,7,11,13,14};byte[][] equation=new byte[8][];
        for(int i=0;i<c.length;i++){equation[i]=new byte[basis[0].length];for(int bit=0;bit<4;bit++)if((c[i]&(1<<bit))!=0)for(int j=0;j<equation[i].length;j++)equation[i][j]^=basis[bit][j];}
        byte[] a=Protocol.encodeFrame(Protocol.PLANE_CODED,Protocol.FLAG_PLANE_WHITENED,0x12345678L,7,1,12,32,900,0,basis[0]);
        byte[] b=Protocol.encodeFrame(Protocol.PLANE_CODED,Protocol.FLAG_PLANE_WHITENED,0x12345678L,7,2,12,32,900,0,basis[1]);
        byte[] d=Protocol.encodeFrame(Protocol.PLANE_CODED,Protocol.FLAG_PLANE_WHITENED,0x12345678L,7,4,12,32,900,0,basis[2]);
        byte[] abc=new byte[a.length];for(int i=0;i<abc.length;i++)abc[i]=(byte)(a[i]^b[i]^d[i]);
        Protocol.Frame parsed=Protocol.parseFrame(abc);assertEquals(Protocol.PLANE_CODED,parsed.kind);assertEquals(7,parsed.globalIndex);assertArrayEquals(equation[4],parsed.payload);
        assertArrayEquals(basis,Protocol.solvePlane4(c,equation));
    }
    private static byte[] hex(String s){byte[] b=new byte[s.length()/2];for(int i=0;i<b.length;i++)b[i]=(byte)Integer.parseInt(s.substring(i*2,i*2+2),16);return b;}
    // First frame in test_vectors/single_file.json, generated by the Python reference codec.
    private static final String VECTOR="44515231010100003860123400000000000000000000000500000000000000000022003083f2f3328acbc37000000000445152430101000000000000000000000000000a0282eeda5f3759df0004524f4f54";
    @Test public void pythonVectorParses(){Protocol.Frame f=Protocol.parseFrame(hex(VECTOR));assertEquals(0x38601234L,f.session);assertEquals(5,f.windowCount);Protocol.Record r=Protocol.parseRecord(f.payload);assertEquals(Protocol.SESSION,r.type);}
    @Test public void whitenedVectorParses(){
        byte[] raw=hex(VECTOR),plainPayload=new byte[raw.length-Protocol.FRAME_HEADER];
        System.arraycopy(raw,Protocol.FRAME_HEADER,plainPayload,0,plainPayload.length);
        ByteBuffer b=ByteBuffer.wrap(raw).order(ByteOrder.BIG_ENDIAN);
        b.putShort(6,(short)Protocol.FLAG_WHITENED);
        long session=Integer.toUnsignedLong(b.getInt(8)),global=Integer.toUnsignedLong(b.getInt(16));
        Protocol.whitenPayload(raw,Protocol.FRAME_HEADER,raw.length-Protocol.FRAME_HEADER,session,global);
        b.putInt(36,(int)Protocol.crc(raw,Protocol.FRAME_HEADER,raw.length-Protocol.FRAME_HEADER));
        b.putInt(40,0);b.putInt(40,(int)Protocol.crc(raw,0,Protocol.FRAME_HEADER));
        Protocol.Frame f=Protocol.parseFrame(raw);
        assertArrayEquals(plainPayload,f.payload);
        assertEquals(Protocol.SESSION,Protocol.parseRecord(f.payload).type);
    }
    @Test public void whiteningHasFixedCrossLanguageSequence(){
        byte[] b=new byte[16];Protocol.whitenPayload(b,0,b.length,0x6A67C69DL,4);
        assertArrayEquals(hex("9d3b1923a8ac39893ead3229f43d3fee"),b);
    }
    private static byte[] record(int id,int size){byte[] body=new byte[size];for(int i=0;i<size;i++)body[i]=(byte)(id*37+i*11);byte[] raw=new byte[Protocol.RECORD_HEADER+size];ByteBuffer b=ByteBuffer.wrap(raw).order(ByteOrder.BIG_ENDIAN);
        b.put("DQRC".getBytes());b.put((byte)1);b.put((byte)Protocol.SESSION);b.putShort((short)0);b.putInt(id);b.putInt(0);b.putInt(size);b.putInt((int)Protocol.crc(body,0,size));b.put(body);return raw;}
    private static Protocol.Frame chain(byte[] a,byte[] b,long left){byte[] x=new byte[Math.max(a.length,b.length)];for(int i=0;i<x.length;i++)x[i]=(byte)((i<a.length?a[i]:0)^(i<b.length?b[i]:0));long lengths=((long)a.length<<16)|b.length;
        return Protocol.parseFrame(Protocol.encodeFrame(Protocol.CHAIN_XOR,Protocol.FLAG_PAIR_WHITENED,0x12345678L,2,left,3,8,lengths,0,x));}
    @Test public void pairedWhiteningMatchesRawDataXor(){byte[] a=record(30,24),b=record(31,24),x=new byte[a.length];for(int i=0;i<x.length;i++)x[i]=(byte)(a[i]^b[i]);
        byte[] ra=Protocol.encodeFrame(Protocol.DATA,Protocol.FLAG_WHITENED,0x12345678L,2,30,0,2,0,0,a);
        byte[] rb=Protocol.encodeFrame(Protocol.DATA,Protocol.FLAG_WHITENED,0x12345678L,2,31,1,2,0,0,b);
        byte[] rx=Protocol.encodeFrame(Protocol.CHAIN_XOR,Protocol.FLAG_PAIR_WHITENED,0x12345678L,2,30,0,2,((long)a.length<<16)|b.length,0,x);
        for(int i=Protocol.FRAME_HEADER;i<rx.length;i++)assertEquals((byte)(ra[i]^rb[i]),rx[i]);
        assertArrayEquals(x,Protocol.parseFrame(rx).payload);}
    @Test public void chainRecoversInBothDirections(){byte[] a=record(10,17),b=record(11,31);Protocol.Frame x=chain(a,b,10);
        assertArrayEquals(b,Protocol.recoverChain(x,a,true));assertArrayEquals(a,Protocol.recoverChain(x,b,false));}
    @Test public void chainPeelsForwardAndBackward(){byte[] a=record(20,9),b=record(21,27),c=record(22,13);Protocol.Frame ab=chain(a,b,20),bc=chain(b,c,21);
        byte[] forwardB=Protocol.recoverChain(ab,a,true);assertArrayEquals(c,Protocol.recoverChain(bc,forwardB,true));
        byte[] backwardB=Protocol.recoverChain(bc,c,false);assertArrayEquals(a,Protocol.recoverChain(ab,backwardB,false));}
    @Test public void blockParityRecoversEveryUnequalMember(){int[] sizes={3,29,7,51,1,18,37};byte[][] payloads=new byte[sizes.length][];int max=0;
        for(int i=0;i<sizes.length;i++){payloads[i]=record(i+1,sizes[i]);max=Math.max(max,payloads[i].length);}
        byte[] parityPayload=new byte[max];for(byte[] payload:payloads)for(int j=0;j<payload.length;j++)parityPayload[j]^=payload[j];
        byte[] wire=Protocol.encodeFrame(Protocol.BLOCK_XOR,Protocol.FLAG_WHITENED,0x6A67C69DL,4,80,0,7,7,0,parityPayload);
        Protocol.Frame parity=Protocol.parseFrame(wire);
        for(int missing=0;missing<payloads.length;missing++){byte[][] members=payloads.clone();members[missing]=null;
            assertArrayEquals(payloads[missing],Protocol.recoverBlock(parity,members,missing));}
    }
    @Test(expected=IllegalArgumentException.class)public void corruptionRejected(){byte[] b=hex(VECTOR);b[b.length-1]^=1;Protocol.parseFrame(b);}
    @Test public void pathRules(){assertEquals("A/B.TXT",Protocol.safePath("A/B.TXT".getBytes(),0,7));for(String p:new String[]{"../X","/X","C:/X","A//B","A\\B"})try{Protocol.safePath(p.getBytes(),0,p.length());fail(p);}catch(IllegalArgumentException expected){}}
}
