apply plugin: 'com.android.application'

android {
    namespace 'org.dosfer.receiver'
    compileSdk 36
    defaultConfig {
        applicationId 'org.dosfer.receiver'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' }
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    testOptions { unitTests.returnDefaultValues = true }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
    testImplementation 'junit:junit:4.13.2'
}
